### ISSUE TITLE
[ERROR] Uploads but does not analyze (docker image)

### ISSUE THREAD

**Issue by CarlesLlobet** [MobSF/Mobile-Security-Framework-MobSF#1295]
## ENVIRONMENT

```
OS and Version: Docker latest image (Ubuntu 18.04.4 LTS (Bionic Beaver))
Python Version: Docker latest image (Python 3.6.9)
MobSF Version: Docker latest image (MobSF v3.0.4 Beta)
```

## EXPLANATION OF THE ISSUE

```
I run a docker instance from the latest image into our tools server, and it deploys smoothly. I can access it instantly from the browser, through our nginx-proxy. 
But whenever I upload an ".apk" o ".ipa", it uploads to 100%, but freezes there, without going into Analyze or doing anything else.

I have tried to modify the shared volume permissions (chmod 777 -R mobsf), and even to deploy the container without volume persistance, and I still can't analyze an app.

Maybe it is related to the nginx-proxy? Some internal re-directions, as it is not in localhost:8000 but in http://mobsf

See [here](https://github.com/nginx-proxy/nginx-proxy) the nginx-proxy documentation.

```

## STEPS TO REPRODUCE THE ISSUE

1. Create the following docker-compose:
```
version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
    environment:
      - DEFAULT_HOST=gitdev
    restart: always

  mobsf_web:
    image: opensecurity/mobile-security-framework-mobsf
    container_name: mobsf_web
    environment:
      - VIRTUAL_HOST=mobsf
      - VIRTUAL_PORT=8000
    volumes:
      - ./mobsf:/root/.MobSF
    ports:
      - "8000:8000"
```
2. Run the container with the following command:
```
docker-compose up -d
```
3. Go to http://mobsf
4. Upload any .apk or .ipa file
5. It uploads smoothly (until 100%) but does not do anything else (see screenshot below)

![image](https://user-images.githubusercontent.com/6575422/75874452-ff5d9700-5e11-11ea-94c6-41b6d970cf42.png)

## LOG FILE

In the docker logs I can't see anything wrong:

```
root@XXXXXXX:/home# docker logs mobsf_web
[2020-03-04 11:05:02 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-03-04 11:05:02 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2020-03-04 11:05:02 +0000] [1] [INFO] Using worker: threads
[2020-03-04 11:05:02 +0000] [8] [INFO] Booting worker with pid: 8
```
